import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { BackGround } from "@/components/background";
import { AppWalletProvider } from "@/AppWalletProvider";

const poppins = Poppins({ weight: "600", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppWalletProvider>
        <body className={`${poppins.className}`} >
          <BackGround />
          {children}
        </body>
      </AppWalletProvider>
    </html>
  );
}
